apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nightly-evaluation
spec:
  schedule: "00 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: evaluation-secret
            secret:
              secretName: evaluation-secret
          containers:
          - image: eu.gcr.io/robco-klose/nightly_cron:latest
            name: nightly-evaluation
            volumeMounts:
            - name: evaluation-secret
              mountPath: /var/secrets/evaluation
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/evaluation/key.json
          restartPolicy: Never
